version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"           # 默认nginx页面
      - "18080:18080"     # hmall-portal前端
      - "18081:18081"     # hmall-admin前端  
      - "18082:18082"     # hm-refresh-admin前端
    volumes:
      # 挂载静态文件
      - ./hmall-nginx/html:/usr/share/nginx/html  # 挂载静态文件目录，ro表示只读模式
      # 挂载日志目录
      - ./hmall-nginx/logs:/var/log/nginx
      # 挂载修正后的nginx配置文件
      - ./hmall-nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
    networks:
      - hmall-network

  # 后端服务（可选，如果需要的话）
  # hmall-backend:
  #   image: openjdk:8-jre-alpine
  #   container_name: hmall-backend
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./hmall/hm-service/target:/app
  #     - ./logs:/app/logs
  #   working_dir: /app
  #   command: java -jar hm-service.jar
  #   environment:
  #     - TZ=Asia/Shanghai
  #   restart: unless-stopped
  #   networks:
  #     - hmall-network

networks:
  hmall-network:
    driver: bridge 