version: '3.8'

services:
  mysql:
    image: mysql:8.0.36
    container_name: hmall-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: hmall
      MYSQL_USER: hmall
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./hmall.sql:/docker-entrypoint-initdb.d/hmall.sql
      - ./hmall.sql:/root/hmall.sql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    labels:
      - createBy=jeanAulis
      - createTime=2025-07-06
    networks:
      - hmall-network

  nginx:
    image: nginx:latest
    container_name: hmall-nginx
    ports:
      - "80:80"           # 默认nginx页面
      - "18080:18080"     # hmall-portal前端
      - "18081:18081"     # hmall-admin前端  
      - "18082:18082"     # hm-refresh-admin前端
    volumes:
      # 挂载静态文件
      - ./hmall-nginx/html:/usr/share/nginx/html  # 挂载静态文件目录，ro表示只读模式
      # 挂载日志目录
      - ./hmall-nginx/logs:/var/log/nginx
      # 挂载修正后的nginx配置文件
      - ./hmall-nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
    labels:
      - createBy=jeanAulis
      - createTime=2025-07-06
    networks:
      - hmall-network
    depends_on:
      - hmall-backend

  # 后端服务
  hmall-backend:
    image: openjdk:11.0-jre-buster
    container_name: hmall-backend
    ports:
      - "8080:8080"
    volumes:
      # 挂载编译好的jar包目录，支持热更新
      - ./hmall/hm-service/target:/app
      # 挂载日志目录
      - ./logs:/app/logs
      # 挂载配置文件（如果需要外部配置）
      - ./hmall/hm-service/src/main/resources:/app/config:ro
    working_dir: /app
    command: java -jar hm-service.jar
    labels:
      - createBy=jeanAulis
      - createTime=2025-07-06
    environment:
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-Xms512m -Xmx1024m -XX:+UseG1GC
    restart: unless-stopped
    networks:
      - hmall-network


volumes:
  mysql_data:

networks:
  hmall-network:
    driver: bridge 